### ISSUE TITLE
simple make target like “run-all-saichallenger-tests” 

### ISSUE THREAD

**Issue by taniazplv** [PLVision/DASH#26]
We need a simple make target like “run-all-saichallenger-tests” which acts like the existing similar commands for pytests and PTF tests. It could be added to the dependencies for “run-all-tests.” No manual entering of containers, making symlinks, etc. should be required. This should all run in the CI pipeline with zero human touch

**Comment by anton7811** [comment]
The target "run-saic-tests" is added in PR #19 But I didn't add it to run-all-tests dependencies since run-saic-tests are in progress and are failing right now.
