### ISSUE TITLE
Add link to general dash-pipeline prerequisites in SAIC readme

### ISSUE THREAD

**Issue by chrispsommers** [PLVision/DASH#36]
In https://github.com/PLVision/DASH/blob/dev-tests-extension/test/docs/dash-test-sai-challenger.md:

Please add directions to follow prerequisites instructions in to https://github.com/Azure/DASH/blob/main/dash-pipeline/README.md#prerequisites (except use a relative link) so people use right VM size, docker-compose version etc.

**Comment by anton7811** [comment]
Fixed in PR #38
